language: node_js
node_js:
- stable

cache:
  directories:
  - node_modules

before_deploy:
      - git config --global user.email "info@extendi.it"
      - git config --global user.name "Travis CI - Extendi"

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: travis-integration