branches:
  only:
    - master
    - gh_pages
    - /^pages-release-.*$/

language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
  - $HOME/.gitbook

script:
  - bash scripts/build.sh

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - react-gate@extendi.it
    on_success: always
    on_failure: always

deploy:
  provider: pages
  local-dir: ./site/_book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^pages-release-.*$
