language: node_js
node_js:
- stable

cache:
  directories:
  - node_modules
dd:
- openssl aes-256-cbc -K $encrypted_4b8c039429e2_key -iv $encrypted_4b8c039429e2_iv
  -in keys.pub.enc -out keys.pub -d

before_deploy:
      - git config --global user.email "info@extendi.it"
      - git config --global user.name "Travis CI - Extendi"

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: travis-integration