language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules


before_script:
  - cp -a node_modules/highlight.js/. ~/.gitbook/versions/$GITBOOK_VERSION/node_modules/highlight.js/

script:
  - yarn build:doc

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - react-gate@extendi.it
    on_success: always
    on_failure: always

cache:
  directories:
    - $HOME/.gitbook

deploy:
  provider: pages
  local-dir: ./site/_book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master