branches:
  only:
    - master
    - gh_pages
    - /^pages-release-.*$/
    - /^npm-release-.*$/

language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
  - $HOME/.gitbook

jobs:
  include:
    - stage: Library Testing
      script: yarn test
    - stage: Github pages release
      script: bash scripts/pages-deploy.sh
      if: tag =~ ^pages-release-.*$
      deploy:
        provider: pages
        local-dir: ./integration-example/build
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        on:
          tags: true
    - stage: Npm package deploy
      script: echo "Npm package deploy" && yarn build
      if: tag =~ ^npm-release-.*$
      deploy:
        provider: npm
        email: info@extendi.it
        skip_cleanup: true
        api_key: $NPM_TOKEN
        on:
          tags: true

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - react-gate@extendi.it
    on_success: always
    on_failure: always