language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notification:
  email:
    recipients:
      - react-gate@extendi.it
    on_success: always
    on_failure: always